[package]
name = "data-access-objects"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "^0.12.0", features = [ "sqlx-postgres", "runtime-async-std-native-tls", "macros" ] }
uuid = { version = "1.9.1", features = ["v4"] }
chrono = "0.4"
models = { path = "../models" }
