version: '3.8'

services:
  database:
    image: paradedb/paradedb:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
