[package]
name = "services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockall = "0.11.1"
uuid = { version = "1.9.1", features = [ "v4", "fast-rng", "macro-diagnostics" ]}
chrono = { version = "0.4.38" }
jsonwebtoken = { version = "9.3.1" }
models = { path = "../models" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sea-orm = { version = "^0.12.0", features = [ "sqlx-postgres", "runtime-async-std-native-tls", "macros" ] }
sha2 = "0.10"
base64 = "0.22"
tracing = "0.1"
lettre = { version = "0.11", default-features = false, features = ["tokio1", "smtp-transport", "builder"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
dotenvy = "0.15"
